/*
 * This file is generated by jOOQ.
 */
package eu.dissco.organisationdemo.database.jooq;


import eu.dissco.organisationdemo.database.jooq.tables.OrganisationDo;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.organisation_do</code>.
     */
    public static final OrganisationDo ORGANISATION_DO = OrganisationDo.ORGANISATION_DO;
}
